apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-simple
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-simple
  template:
    metadata:
      labels:
        app: guestbook-simple
    spec:
      containers:
        - image: europe-west4-docker.pkg.dev/shared-9456/sng/guestbook:latest
          name: guestbook-simple
          ports:
            - name: http
              containerPort: 3000
