apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: guestbook-dev
images:
  - name: europe-west4-docker.pkg.dev/shared-9456/sng/guestbook
    newTag: 3.0.0
configMapGenerator:
  - name: app-config
    literals:
      - ENV=development
      - LOG_LEVEL=debug
      - hoi=doei2
    behavior: create
